# Generated by Django 4.1.2 on 2023-04-18 23:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("competitions", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Competitions",
            new_name="Competition",
        ),
        migrations.RenameModel(
            old_name="Competitors",
            new_name="Competitor",
        ),
    ]
