# Generated by Django 4.1.2 on 2023-04-18 23:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competitions", "0002_rename_competitions_competition_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="competition",
            name="competitors",
        ),
        migrations.AddField(
            model_name="competition",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="competitor",
            name="competition",
            field=models.ManyToManyField(
                related_name="competitors", to="competitions.competition"
            ),
        ),
    ]
