# Generated by Django 4.1.2 on 2023-04-18 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "competitions",
            "0003_remove_competition_competitors_competition_is_active_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="competitor",
            name="competition",
        ),
        migrations.AddField(
            model_name="competitor",
            name="competition",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="competitors",
                to="competitions.competition",
            ),
            preserve_default=False,
        ),
    ]
