# Generated by Django 4.1.2 on 2023-04-18 23:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competitions", "0004_remove_competitor_competition_competitor_competition"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="competitor",
            name="competition",
        ),
        migrations.AddField(
            model_name="competition",
            name="competitor",
            field=models.ManyToManyField(
                related_name="competitor", to="competitions.competitor"
            ),
        ),
    ]
