# Generated by Django 4.1.2 on 2023-04-18 23:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("competitions", "0005_remove_competitor_competition_competition_competitor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competition",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="competitor",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
