# Generated by Django 4.1.2 on 2023-04-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competitions", "0007_competitor_ranking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competition",
            name="name",
            field=models.CharField(max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name="competitor",
            name="email",
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
