# Generated by Django 4.1.2 on 2023-04-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="banner",
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
