# Generated by Django 4.1.2 on 2023-04-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0002_alter_club_banner"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubmember",
            name="reason",
            field=models.CharField(default=111, max_length=300),
            preserve_default=False,
        ),
    ]
