# Generated by Django 4.1.2 on 2023-04-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0003_clubmember_reason"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClubDomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain", models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name="ClubRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        default=(
                            ("1", "Member"),
                            ("2", "Lead"),
                            ("3", "Co-Lead"),
                            ("4", "Director"),
                            ("5", "Co-Director"),
                            ("6", "Volunteer"),
                            ("7", "Manager"),
                        ),
                        max_length=40,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="club",
            name="domain",
            field=models.ManyToManyField(related_name="domain", to="clubs.clubrole"),
        ),
        migrations.AddField(
            model_name="club",
            name="role",
            field=models.ManyToManyField(related_name="roles", to="clubs.clubrole"),
        ),
    ]
