# Generated by Django 4.1.2 on 2023-04-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0004_clubdomain_clubrole_club_domain_club_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clubrole",
            name="role",
            field=models.CharField(
                choices=[
                    ("1", "Member"),
                    ("2", "Lead"),
                    ("3", "Co-Lead"),
                    ("4", "Director"),
                    ("5", "Co-Director"),
                    ("6", "Volunteer"),
                    ("7", "Manager"),
                ],
                max_length=40,
            ),
        ),
    ]
