# Generated by Django 4.1.2 on 2023-04-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0005_alter_clubrole_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="domain",
            field=models.ManyToManyField(related_name="domains", to="clubs.clubdomain"),
        ),
    ]
