# Generated by Django 4.1.2 on 2023-04-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0006_alter_club_domain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clubrole",
            name="role",
            field=models.CharField(
                choices=[
                    ("Member", "Member"),
                    ("Lead", "Lead"),
                    ("Co-Lead", "Co-Lead"),
                    ("Director", "Director"),
                    ("Co-Director", "Co-Director"),
                    ("Volunteer", "Volunteer"),
                    ("Manager", "Manager"),
                ],
                max_length=40,
            ),
        ),
    ]
