# Generated by Django 4.1.2 on 2023-04-04 00:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0007_alter_clubrole_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="is_accepted",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
