# Generated by Django 4.1.2 on 2023-04-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0009_club_rejected"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="is_accepted",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="club",
            name="rejected",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
