# Generated by Django 4.1.2 on 2023-04-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0010_alter_club_is_accepted_alter_club_rejected"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="is_accepted",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="club",
            name="rejected",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
