# Generated by Django 4.1.2 on 2023-04-06 16:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clubs", "0011_alter_club_is_accepted_alter_club_rejected"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubevent",
            name="end_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="clubevent",
            name="going",
            field=models.ManyToManyField(default=[], to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="clubevent",
            name="start_date",
            field=models.DateField(null=True),
        ),
    ]
