# Generated by Django 4.1.2 on 2023-04-06 16:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clubs", "0012_clubevent_end_date_clubevent_going_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clubevent",
            name="end_date",
            field=models.DateField(default="2023-3-4"),
        ),
        migrations.AlterField(
            model_name="clubevent",
            name="going",
            field=models.ManyToManyField(
                default=[], null=True, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="clubevent",
            name="start_date",
            field=models.DateField(default="2023-3-4"),
        ),
    ]
