# Generated by Django 4.1.2 on 2023-04-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0014_remove_clubevent_club_remove_clubevent_going_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clubrole",
            name="role",
            field=models.CharField(max_length=40),
        ),
    ]
