# Generated by Django 4.1.2 on 2023-04-10 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clubs", "0018_clubevent_no_of_registrations_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventRegistrations",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("registering_user_email", models.CharField(max_length=30)),
                (
                    "of_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="of_delete",
                        to="clubs.clubevent",
                    ),
                ),
                (
                    "registration_for_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registration_for_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
