# Generated by Django 4.1.2 on 2023-04-10 21:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0020_alter_clubevent_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clubevent",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
