# Generated by Django 4.1.2 on 2023-04-10 21:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0022_alter_clubevent_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clubevent",
            name="end_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="clubevent",
            name="start_date",
            field=models.DateField(),
        ),
    ]
