# Generated by Django 4.1.2 on 2023-04-11 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0024_alter_clubevent_end_date_alter_clubevent_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubevent",
            name="banner",
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="clubevent",
            name="registration_status",
            field=models.CharField(
                choices=[
                    ("Ongoing", "Ongoing"),
                    ("Up-Coming", "Up-Coming"),
                    ("Past", "Previous"),
                ],
                default="Up-Coming",
                max_length=20,
            ),
        ),
    ]
