# Generated by Django 4.1.2 on 2023-04-13 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clubs", "0026_rename_eventregistrations_eventregistration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventregistration",
            name="registration_for_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registration_for_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
