# Generated by Django 4.1.2 on 2023-04-15 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0027_alter_eventregistration_registration_for_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventregistration",
            name="of_event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="of_event",
                to="clubs.clubevent",
            ),
        ),
        migrations.AlterField(
            model_name="eventregistration",
            name="registering_user_email",
            field=models.EmailField(max_length=30),
        ),
    ]
