# Generated by Django 4.1.2 on 2023-04-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0028_alter_eventregistration_of_event_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="description",
            field=models.CharField(max_length=250),
        ),
    ]
