# Generated by Django 4.1.2 on 2023-04-18 21:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0029_alter_club_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="clubevent",
            old_name="registration_left",
            new_name="registrations_made",
        ),
    ]
