# Generated by Django 4.1.2 on 2023-04-18 22:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0032_alter_clubevent_registration_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clubevent",
            name="registration_status",
            field=models.CharField(
                blank=True, default="Up-Coming", max_length=20, null=True
            ),
        ),
    ]
