# Generated by Django 4.1.2 on 2023-04-18 22:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0033_alter_clubevent_registration_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clubevent",
            name="registration_status",
            field=models.CharField(
                choices=[
                    ("Ongoing", "Ongoing"),
                    ("Up-Coming", "Up-Coming"),
                    ("Past", "Previous"),
                ],
                default="Up-Coming",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="clubevent",
            name="registrations_made",
            field=models.IntegerField(
                default=0,
                help_text="No of registrations that have been made i.e. 32/40",
            ),
        ),
    ]
