# Generated by Django 4.1.2 on 2023-04-12 03:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
