# Generated by Django 4.1.2 on 2023-04-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_alter_post_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="description",
            field=models.CharField(max_length=1500),
        ),
    ]
