# Generated by Django 4.1.2 on 2023-03-28 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_category_club_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="tags",
            field=models.CharField(max_length=40),
        ),
        migrations.CreateModel(
            name="ClubRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rule", models.CharField(max_length=200)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="rule_club",
                        to="users.club",
                    ),
                ),
            ],
        ),
    ]
