# Generated by Django 4.1.2 on 2023-03-29 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_category_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClubEvents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("description", models.CharField(max_length=200)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="event_club",
                        to="users.club",
                    ),
                ),
            ],
        ),
    ]
