# Generated by Django 4.1.2 on 2023-03-29 20:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_clubevents"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ClubEvents",
            new_name="ClubEvent",
        ),
    ]
