# Generated by Django 4.1.2 on 2023-03-30 23:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_alter_user_phonenumber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lead_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="clubevent",
            name="club",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="event_club",
                to="users.club",
            ),
        ),
        migrations.AlterField(
            model_name="clubmember",
            name="club",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="club",
                to="users.club",
            ),
        ),
        migrations.AlterField(
            model_name="clubmember",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="clubrule",
            name="club",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rule_club",
                to="users.club",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_pic",
            field=models.CharField(
                default="https://firebasestorage.googleapis.com/v0/b/schoolmanagement-api-df5f5.appspot.com/o/coding_club-api%2Fmedia%2Fprofile_pic%2Fprofile-icon.jpg?alt=media&token=95653be4-0f70-4403-8827-d60560c59d92",
                max_length=400,
            ),
        ),
    ]
