# Generated by Django 4.1.2 on 2023-03-31 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_alter_club_user_alter_clubevent_club_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clubevent",
            name="club",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_club",
                to="users.club",
            ),
        ),
        migrations.AlterField(
            model_name="clubrule",
            name="club",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rule_club",
                to="users.club",
            ),
        ),
    ]
