# Generated by Django 4.1.2 on 2023-04-01 09:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0014_alter_clubmember_club_alter_clubmember_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="club",
            old_name="user",
            new_name="lead_user",
        ),
    ]
