# Generated by Django 4.1.2 on 2023-04-01 12:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0015_rename_user_club_lead_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="club",
            name="category",
        ),
        migrations.RemoveField(
            model_name="club",
            name="lead_user",
        ),
        migrations.RemoveField(
            model_name="clubevent",
            name="club",
        ),
        migrations.RemoveField(
            model_name="clubmember",
            name="club",
        ),
        migrations.RemoveField(
            model_name="clubmember",
            name="user",
        ),
        migrations.RemoveField(
            model_name="clubrule",
            name="club",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="Club",
        ),
        migrations.DeleteModel(
            name="ClubEvent",
        ),
        migrations.DeleteModel(
            name="ClubMember",
        ),
        migrations.DeleteModel(
            name="ClubRule",
        ),
    ]
