# Generated by Django 4.1.2 on 2023-04-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0016_remove_club_category_remove_club_lead_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                default=(("1", "Male"), ("2", "Female"), ("3", "Other")), max_length=10
            ),
        ),
    ]
