# Generated by Django 4.1.2 on 2023-04-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0017_user_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("1", "Male"), ("2", "Female"), ("3", "Other")], max_length=10
            ),
        ),
    ]
