# Generated by Django 4.1.2 on 2023-04-02 22:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0018_alter_user_gender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="gender",
        ),
    ]
