# Generated by Django 4.1.2 on 2023-04-04 00:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0020_remove_user_groups_user_gender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="user_permissions",
        ),
        migrations.AddField(
            model_name="user",
            name="facebook",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="linkedIn",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="twitter",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_pic",
            field=models.CharField(
                default="https://firebasestorage.googleapis.com/v0/b/schoolmanagement-api-df5f5.appspot.com/o/coding_club-api%2Fmedia%2Fprofile_pic%2F9d1ad717-b868-40b3-98fb-03cfadef2c2e%20_%20mm.jpg?alt=media",
                max_length=400,
            ),
        ),
    ]
