# Generated by Django 4.1.2 on 2023-04-06 21:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0021_remove_user_user_permissions_user_facebook_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("otp", models.CharField(max_length=11)),
            ],
        ),
    ]
