# Generated by Django 4.1.2 on 2023-04-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0022_otp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="facebook",
            field=models.CharField(blank=True, default="No Link", max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="linkedIn",
            field=models.CharField(blank=True, default="No Link", max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="twitter",
            field=models.CharField(blank=True, default="No Link", max_length=200),
            preserve_default=False,
        ),
    ]
